version: 2

sources:
  - name: sales_raw
    database: daily-sales-learning
    schema: sales_raw
    tables:
      - name: sales_daily
        description: Raw daily sales file loaded from GCS into BigQuery.
